version: "3"

services:
  producer:
    container_name: twittersentimentanalysis_producer
    build: "./produce-tweets"
    depends_on:
      - kafka
      - influxdb
    restart: on-failure
    # command: >
    #   python run.py
    volumes:
      - ./produce-tweets:/produce-tweets
      - ./config.ini:/produce-tweets/config.ini

  consumer:
    container_name: twittersentimentanalysis_consumer
    build: "./consume-tweets"
    depends_on:
      - kafka
      - influxdb
    restart: on-failure
    # command: >
    #   python run.py
    volumes:
      - ./consume-tweets:/consume-tweets
      - ./config.ini:/consume-tweets/config.ini
      - ./model/model.pickle:/consume-tweets/model.pickle

  zookeeper:
    container_name: twittersentimentanalysis_zookeeper
    image: wurstmeister/zookeeper:3.4.6
    restart: on-failure
    expose:
      - "2181"

  kafka:
    container_name: twittersentimentanalysis_kafka
    image: wurstmeister/kafka:2.12-2.4.0
    depends_on:
      - zookeeper
    restart: on-failure
    ports:
      - "9092:9092"
    expose:
      - "9093"
    volumes:
      - ./persistence/kafka:/tmp/kafka-logs
    environment:
      - "KAFKA_BROKER_ID=1"
      - "KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      - "KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092"
      - "KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_CREATE_TOPICS=tweets:1:1"
      - "KAFKA_LOG_DIRS=/tmp/kafka-logs"
      - "KAFKA_LOG_RETENTION_HOURS=24"
      - "KAFKA_LOG_CLEANUP_POLICY=delete"

  influxdb:
    container_name: twittersentimentanalysis_influxdb
    image: influxdb:1.7.10
    restart: on-failure
    ports:
      - "8086:8086"
    volumes:
      - ./persistence/influxdb:/var/lib/influxdb
    environment:
      - "INFLUXDB_GRAPHITE_ENABLED=false"

  grafana:
    container_name: twittersentimentanalysis_grafana
    image: grafana/grafana:6.5.2
    restart: on-failure
    environment:
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_org_name=Main Org."
      - "GF_AUTH_ANONYMOUS_org_role=Admin"
    ports: 
      - "80:3000"
    volumes:
      - ./persistence/grafana:/var/lib/grafana

networks:
  default:
    external:
      name: twittersentimentanalysis_network